import{S as v,i as S}from"./assets/vendor-0fc460d7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();function y(r,e,a){return axios.get("https://pixabay.com/api/",{params:{key:"45153931-2470322a6efc3ba9ceddb2cb4",image_type:"photo",orientation:"horizontal",safesearch:!0,q:r,per_page:a,page:e}})}let f=new v(".img-list a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function b(r,e){const a=r.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
            <img
            class="gallery-img"
            src="${s.webformatURL}"
            data-source="${s.largeImageURL}"
            alt="${s.tags}">
            </a>
            <div class="img-description">
              <p class="description-text">Likes <span class="description-value"> ${s.likes}</span></p>
              <p class="description-text">Views <span class="description-value"> ${s.views}</span></p>
              <p class="description-text">Comments <span class="description-value"> ${s.comments}</span></p>
              <p class="description-text">Downloads <span class="description-value"> ${s.downloads}</span></p>
            </div>
              </li>`).join("");e.insertAdjacentHTML("beforeend",a),f.on("show.simplelightbox",function(){}),f.refresh()}const E=document.querySelector(".search-form"),x=document.querySelector(".search-input"),p=document.querySelector(".img-list"),m=document.querySelector(".load-more-btn"),P=document.querySelector(".loader");function g(r){S.error({message:r,position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",iconColor:"#fff",icon:"fa-regular fa-circle-xmark",progressBarColor:"#B51B1B",maxWidth:432,messageSize:"16"})}let c=1;const h=15;let l,d;class L{constructor(e,a){this.buttonEL=e,this.hiddenClass=a}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const i=new L(m,"is-hidden"),n=new L(P,"is-hidden");i.hide();n.hide();E.addEventListener("submit",$);async function $(r){if(r.preventDefault(),i.hide(),p.innerHTML="",d=x.value.trim(),n.show(),d===""){i.hide(),n.hide(),g("Please fill the search field!");return}else{c=1;try{const e=await y(d,c,h);console.log(e);const a=e.data.hits,s=e.data.totalHits;l=Math.ceil(s/h),console.log(l),s>0?(i.show(),i.disable(),b(a,p),n.hide()):(n.hide(),g("Sorry, there are no images matching your search query. Please try again!"),i.hide()),l>1?(i.enable(),m.addEventListener("click",w)):i.hide()}catch(e){console.log(`Помилка під час запиту: ${e.message}`)}finally{r.currentTarget.reset()}}}async function w(){i.disable(),c=c+1,n.show();try{const e=(await y(d,c,h)).data.hits;b(e,p),n.hide()}catch(r){console.error(`Error during request: ${r.message}`)}finally{c===l?(i.hide(),m.removeEventListener("click",w)):i.enable()}}
//# sourceMappingURL=commonHelpers.js.map
