import{S as L,i as v}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();function h(s,t,a){return axios.get("https://pixabay.com/api/",{params:{key:"45153931-2470322a6efc3ba9ceddb2cb4",image_type:"photo",orientation:"horizontal",safesearch:!0,q:s,per_page:a,page:t}})}let m=new L(".img-list a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function g(s,t){const a=s.map(r=>`<li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
            <img
            class="gallery-img"
            src="${r.webformatURL}"
            data-source="${r.largeImageURL}"
            alt="${r.tags}">
            </a>
            <div class="img-description">
              <p class="description-text">Likes <span class="description-value"> ${r.likes}</span></p>
              <p class="description-text">Views <span class="description-value"> ${r.views}</span></p>
              <p class="description-text">Comments <span class="description-value"> ${r.comments}</span></p>
              <p class="description-text">Downloads <span class="description-value"> ${r.downloads}</span></p>
            </div>
              </li>`).join("");t.insertAdjacentHTML("beforeend",a),m.on("show.simplelightbox",function(){}),m.refresh()}const w=document.querySelector(".search-form"),y=document.querySelector(".search-input"),d=document.querySelector(".img-list"),p=document.querySelector(".load-more-btn");function f(s){v.error({message:s,position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",iconColor:"#fff",icon:"fa-regular fa-circle-xmark",progressBarColor:"#B51B1B",maxWidth:432,messageSize:"16"})}let n=1;const u=15;let c;class S{constructor(t,a){this.buttonEL=t,this.hiddenClass=a}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const i=new S(p,"is-hidden");i.hide();w.addEventListener("submit",E);async function E(s){s.preventDefault(),d.innerHTML="";const t=y.value.trim();if(t===""){f("Please fill the search field!");return}else{n=1;try{const a=await h(t,n,u),r=a.data.hits,e=a.data.total;c=Math.ceil(e/u),console.log(c),e>0?(i.show(),i.disable(),g(r,d)):f("Sorry, there are no images matching your search query. Please try again!"),c>1?(i.enable(),p.addEventListener("click",b)):i.hide()}catch(a){console.log(`Помилка під час запиту: ${a.message}`)}finally{s.currentTarget.reset()}}}async function b(){i.disable(),n++;try{const t=(await h(y.value.trim(),n,u)).data.hits;g(t,d)}catch(s){console.error(`Error during request: ${s.message}`)}finally{n===c?(i.hide(),p.removeEventListener("click",b)):i.enable()}}
//# sourceMappingURL=commonHelpers.js.map
